lab1tokenizer: simpleui.o tokenizer.o history.o
		cc -o lab1tokenizer simpleui.o tokenizer.o history.o

simpleui.o: simpleui.c history.h tokenizer.h

tokenizer.o: tokenizer.h tokenizer.c

history.o: history.h history.c
